title: Livid
author: Livid
email: livid@v2ex.com
description: > # this means to ignore newlines until "twitter_username:"
  Beautifully Advance
url: https://livid.v2ex.com

# social links
twitter_username: livid
# github_username:  livid
rss: rss
# dribbble_username: livid
# facebook_username: jekyll
# flickr_username: jekyll
# instagram_username: livid
# linkedin_username: jekyll
# pinterest_username: jekyll
# youtube_username: jekyll
# googleplus_username: +jekyll

google_analytics: UA-11940834-17

# Mastodon instances
# mastodon:
# - username: jekyll
#   instance: example.com
# - username: jekyll2
#   instance: example.com


show_excerpts: false # set to true to show excerpts on the homepage

# Minima date format
# refer to http://shopify.github.io/liquid/filters/date/ if you want to customize this
minima:
  date_format: "%b %-d, %Y"

# If you want to link only specific pages in your header, uncomment
# this and add the path to the pages in order as they should show up
#header_pages:
# - about.html

# Build settings
theme: minima

plugins:
 - jekyll-feed
 - jekyll-seo-tag
 - jekyll-relative-links

exclude:
 - .ruby-gemset
 - .ruby-version
 - Gemfile
 - Gemfile.lock
 - minima.gemspec
 - Makefile
 - README.md
 - vendor/
